version: "3.6"
services:
  messenger:
    restart: always
    build:
      context: ./messenger
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${MESSENGER_PORT}:8080"
    volumes:
      - ./messenger:/app

  celery_worker:
    restart: always
    build:
      context: ./messenger
      dockerfile: ./DockerfileWorker
    env_file:
      - .env
    volumes:
      - ./messenger:/app

  postprocessor:
    restart: always
    build:
      context: ./postprocessor
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${POSTPROCESSOR_PORT}:8080"
    volumes:
      - ./postprocessor:/app

  flower:
    container_name: flower
    image: mher/flower:0.9.5
    build: .
    command: [
      "flower",
      "--broker=${AMQP_URI}",
    ]
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    env_file:
      - .env
    depends_on:
      - celery_worker
      - messenger